version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3

    steps:
      - checkout

      - run:
          name: Install awscli
          command: sudo pip install awscli

      - run: 
          name: Copy files to S3
          command: aws s3 cp src s3://mtg.emshea.com --grant read=uri=http://acs.amazonaws.com/groups/global/AllUsers --recursive